### ISSUE TITLE
ERROR: TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by alekks** [GumbyFramework/Claymate#5]
A couple of weeks ago, when I latest used `$ claymate install` there was no problem, but for a few days now I haven't been able to run the command. Just get the following error:
ERROR: TypeError: Arguments to path.join must be strings

Even though I haven't updated anything since then I've tried to reinstall, update, revert to an earlier version, clearing caches but still no luck.

Thougt that it might have something to do with the same error message bower spitted out a month a go, but can't seem to find any similarites in e.g. dependencies or stuff like that.

Oh, and currently (after messing around) using, if it's to any help:
node 0.10.30
npm 2.0.0-alpha-5
claymate 2.0.4
bower 1.3.9

Update: from no where it just started working again.

**Comment by funerr** [comment]
+1
