### ISSUE TITLE
ERROR: TypeError: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by agamm** [GumbyFramework/Claymate#8]
`claymate install` returns:
`ERROR: TypeError: Arguments to path.join must be strings`

Working from:
Windows 7 
node v0.10.35
npm 1.4.28
bower 1.3.8

How can I fix this?

**Comment by joetjen** [comment]
what worked for me is installing gumpy with `bower install gumpy` before running `claymate install`.

**Comment by funerr** [comment]
@joetjen , it did work (typo though: `gumby` not `gumpy`). Now I get a more specific claymate error.
Shouldn't this be fixed in the manual version?
